### ISSUE TITLE
Fetch and serve the mini-dashboard

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/transplant#87]
I thought a little bit about how we can fetch [the mini-dashboard sources](https://github.com/meilisearch/interface/releases/tag/v0.1.0) (js, CSS, and HTML files) and make the meilisearch HTTP server serves them.

To make it idiomatic and easy for Rust developers to work with external sources, I find out that [there is a `metadata` section in the `Cargo.toml` configuration file](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table). This section would help us specify the files that we must generate routes about.

```toml
[package]
name = "meilisearch"
# ...

# Metadata used when fetching the mini-dashboard sources.
# Will be downloaded and extracted in the /target/mini-dashboard directory.
[package.metadata.mini-dashboard]
assets-url = "https://github.com/meilisearch/interface/releases/tag/v0.1.0"
assets-files = ["index.html", "script.js", "style.css"]
```

Obviously, those metadata doesn't do anything by themselves. This will be combined with [a custom build script (`build.rs`)](https://doc.rust-lang.org/cargo/reference/build-scripts.html) and maybe something to [statically import the content of a folder in the project](https://lib.rs/crates/include_dir).

Using [a zip library](https://lib.rs/crates/zip) to unzip the mini-dashboard source files in the `/target/mini-dashboard` directory, we will have a list of files that we must serve. The directory's content must be checked with the `assets-files` metadata to ensure that all the routes will be generated (there must not be one missing file or one more file than the ones in this list).

Once we know that the content is valid and expected, we must generate a route for each of the assets, following the directory hierarchy. I am not sure how to do that; macros will surely help us do so. We must keep in mind that the content must be served with a valid content-type header (`application/js`, `text/css`...). This can easily be defined file by file.

```rust
generate_asset_route!(style_css_content, "/public/style.css");
generate_asset_route!(script_js_content, "/public/script.js");
generate_asset_route!(index_html_content, "/");
```
